CHIELDOnline/CHIELD

data/tree/documents/1970s/1976/chomsky1976reflections/chomsky1976reflections.bib
data/tree/documents/1970s/1976/chomsky1976reflections/chomsky1976reflections_links.csv
data/tree/documents/1970s/1976/chomsky1976reflections/contributors.txt

Add chomsky1976reflections from seannyD

Add chomsky1976reflections

---

data/tree/documents/2010s/2017/holler2017processing/contributors.txt
data/tree/documents/2010s/2017/holler2017processing/holler2017processing.bib
data/tree/documents/2010s/2017/holler2017processing/holler2017processing_links.csv

Add holler2017processing from seannyD

Add holler2017processing

---

data/tree/documents/2010s/2017/holler2017processing333/contributors.txt
data/tree/documents/2010s/2017/holler2017processing333/holler2017processing333.bib
data/tree/documents/2010s/2017/holler2017processing333/holler2017processing333_links.csv

Add holler2017processing333 from seannyD

Add holler2017processing333

---

data/tree/documents/1990s/1999/gregory1999effects/contributors.txt
data/tree/documents/1990s/1999/gregory1999effects/gregory1999effects.bib
data/tree/documents/1990s/1999/gregory1999effects/gregory1999effects.csv

Add gregory1999effects from seannyD	Sean Roberts	Mon Mar 26 2018 12:40:36 GMT+0100 (BST)

Add gregory1999effects

---

data/tree/documents/1980s/1986/crocker1986introduction/contributors.txt
data/tree/documents/1980s/1986/crocker1986introduction/crocker1986introduction.bib
data/tree/documents/1980s/1986/crocker1986introduction/crocker1986introduction.csv

Add crocker1986introduction from seannyD	Sean Roberts	Mon Mar 26 2018 13:41:06 GMT+0100 (BST)

Add crocker1986introduction

---

data/tree/documents/2010s/2018/evolang12/contributors.txt
data/tree/documents/2010s/2018/evolang12/evolang12.bib
data/tree/documents/2010s/2018/evolang12/evolang12.csv

Add evolang12 from Limor-Raviv	Limor Raviv	Tue Mar 27 2018 14:14:39 GMT+0200 (W. Europe Daylight Time)

Add evolang12

---

data/tree/documents/1990s/1995/MacePagel1995/MacePagel1995.bib
data/tree/documents/1990s/1995/MacePagel1995/MacePagel1995.csv
data/tree/documents/1990s/1995/MacePagel1995/contributors.txt

Add MacePagel1995 from SimonGreenhill	Simon J Greenhill	Tue Mar 27 2018 13:40:35 GMT+0200 (CEST)

Add MacePagel1995

---

data/tree/documents/2010s/2011/Calude2011/Calude2011.bib
data/tree/documents/2010s/2011/Calude2011/Calude2011.csv
data/tree/documents/2010s/2011/Calude2011/contributors.txt

Add Calude2011 from SimonGreenhill	Simon J Greenhill	Tue Mar 27 2018 13:08:17 GMT+0200 (CEST)

Add Calude2011

---

data/tree/documents/1970s/1974/trudgill1974linguistic/contributors.txt
data/tree/documents/1970s/1974/trudgill1974linguistic/trudgill1974linguistic.bib
data/tree/documents/1970s/1974/trudgill1974linguistic/trudgill1974linguistic.csv

Add trudgill1974linguistic from SeanSLee	Sean Lee	Wed Mar 28 2018 12:28:00 GMT+0900 (JST)

Add trudgill1974linguistic

---

data/tree/documents/2010s/2014/axelsen2014river/axelsen2014river.bib
data/tree/documents/2010s/2014/axelsen2014river/axelsen2014river.csv
data/tree/documents/2010s/2014/axelsen2014river/contributors.txt

Add axelsen2014river from SeanSLee	Sean Lee	Wed Mar 28 2018 12:45:11 GMT+0900 (JST)

Add axelsen2014river

---

data/tree/documents/2010s/2014/lee2014oceanic/contributors.txt
data/tree/documents/2010s/2014/lee2014oceanic/lee2014oceanic.bib
data/tree/documents/2010s/2014/lee2014oceanic/lee2014oceanic.csv

Add lee2014oceanic from SeanSLee	Sean Lee	Wed Mar 28 2018 12:48:36 GMT+0900 (JST)

Add lee2014oceanic

---

data/tree/documents/2010s/2015/bromham2015rate/bromham2015rate.bib
data/tree/documents/2010s/2015/bromham2015rate/bromham2015rate.csv
data/tree/documents/2010s/2015/bromham2015rate/contributors.txt

Add bromham2015rate from SeanSLee	Sean Lee	Wed Mar 28 2018 15:02:32 GMT+0900 (JST)

Add bromham2015rate

---

data/tree/documents/2010s/2013/miyagawa2013emergence/contributors.txt
data/tree/documents/2010s/2013/miyagawa2013emergence/miyagawa2013emergence.bib
data/tree/documents/2010s/2013/miyagawa2013emergence/miyagawa2013emergence.csv

Add miyagawa2013emergence from SeanSLee	Sean Lee	Wed Mar 28 2018 16:11:59 GMT+0900 (JST)

Add miyagawa2013emergence

---

data/tree/documents/2000s/2008/10.1111/j.0030-1299.2008.16684.x/10.1111/j.0030-1299.2008.16684.x.bib
data/tree/documents/2000s/2008/10.1111/j.0030-1299.2008.16684.x/10.1111/j.0030-1299.2008.16684.x.csv
data/tree/documents/2000s/2008/10.1111/j.0030-1299.2008.16684.x/contributors.txt

Add 10.1111/j.0030-1299.2008.16684.x from SimonGreenhill	Simon J Greenhill	Wed Mar 28 2018 10:11:56 GMT+0200 (CEST)

Add 10.1111/j.0030-1299.2008.16684.x

---

data/tree/documents/2010s/2014/TurveyPettorelli2014/TurveyPettorelli2014.bib
data/tree/documents/2010s/2014/TurveyPettorelli2014/TurveyPettorelli2014.csv
data/tree/documents/2010s/2014/TurveyPettorelli2014/contributors.txt

Add TurveyPettorelli2014 from SimonGreenhill	Simon J Greenhill	Wed Mar 28 2018 17:03:05 GMT+0200 (CEST)

Add TurveyPettorelli2014

---

data/tree/documents/2010s/2015/okanoya2015evolution/contributors.txt
data/tree/documents/2010s/2015/okanoya2015evolution/okanoya2015evolution.bib
data/tree/documents/2010s/2015/okanoya2015evolution/okanoya2015evolution.csv

Add okanoya2015evolution from SeanSLee	Sean Lee	Wed Mar 28 2018 12:57:15 GMT+0900 (JST)

Add okanoya2015evolution

---

data/tree/documents/1990s/1992/Dunbar1992/Dunbar1992.bib
data/tree/documents/1990s/1992/Dunbar1992/Dunbar1992.csv
data/tree/documents/1990s/1992/Dunbar1992/contributors.txt

Add Dunbar1992 from SimonGreenhill	Simon J Greenhill	Fri Mar 30 2018 15:40:40 GMT+0200 (CEST)

Add Dunbar1992

---

data/tree/documents/2010s/2010/galantucci2010effects/contributors.txt
data/tree/documents/2010s/2010/galantucci2010effects/galantucci2010effects.bib
data/tree/documents/2010s/2010/galantucci2010effects/galantucci2010effects.csv

Add galantucci2010effects from hanachronism	Hannah Little	Sat Mar 31 2018 11:02:36 GMT+0200 (CEST)

Add galantucci2010effects

---

data/tree/documents/2010s/2014/verhoef2014emergence/contributors.txt
data/tree/documents/2010s/2014/verhoef2014emergence/verhoef2014emergence.bib
data/tree/documents/2010s/2014/verhoef2014emergence/verhoef2014emergence.csv

Add verhoef2014emergence from hanachronism	Hannah Little	Sat Mar 31 2018 11:11:11 GMT+0200 (CEST)

Add verhoef2014emergence

---

data/tree/documents/2010s/2016/verhoef2016iconicity/contributors.txt
data/tree/documents/2010s/2016/verhoef2016iconicity/verhoef2016iconicity.bib
data/tree/documents/2010s/2016/verhoef2016iconicity/verhoef2016iconicity.csv

Add verhoef2016iconicity from hanachronism	Hannah Little	Sat Mar 31 2018 11:26:50 GMT+0200 (CEST)

Add verhoef2016iconicity

---

data/tree/documents/2010s/2015/roberts2015communication/contributors.txt
data/tree/documents/2010s/2015/roberts2015communication/roberts2015communication.bib
data/tree/documents/2010s/2015/roberts2015communication/roberts2015communication.csv

Add roberts2015communication from hanachronism	Hannah Little	Sat Mar 31 2018 11:31:17 GMT+0200 (CEST)

Add roberts2015communication

---

data/tree/documents/2010s/2012/roberts2012emergence/contributors.txt
data/tree/documents/2010s/2012/roberts2012emergence/roberts2012emergence.bib
data/tree/documents/2010s/2012/roberts2012emergence/roberts2012emergence.csv

Add roberts2012emergence from hanachronism	Hannah Little	Sat Mar 31 2018 11:39:11 GMT+0200 (CEST)

Add roberts2012emergence

---

data/tree/documents/1960s/1960/hockett/contributors.txt
data/tree/documents/1960s/1960/hockett/hockett.bib
data/tree/documents/1960s/1960/hockett/hockett.csv

Add hockett from hanachronism	Hannah Little	Sat Mar 31 2018 11:41:05 GMT+0200 (CEST)

Add hockett

---

data/tree/documents/2010s/2017/little2017signal/contributors.txt
data/tree/documents/2010s/2017/little2017signal/little2017signal.bib
data/tree/documents/2010s/2017/little2017signal/little2017signal.csv

Add little2017signal from hanachronism	Hannah Little	Sat Mar 31 2018 11:53:10 GMT+0200 (CEST)

Add little2017signal

---

data/tree/documents/2010s/2017/little2017conventionalisation/contributors.txt
data/tree/documents/2010s/2017/little2017conventionalisation/little2017conventionalisation.bib
data/tree/documents/2010s/2017/little2017conventionalisation/little2017conventionalisation.csv

Add little2017conventionalisation from hanachronism	Hannah Little	Sat Mar 31 2018 11:57:32 GMT+0200 (CEST)

Add little2017conventionalisation

---

data/tree/documents/2010s/2014/fay2014creating/contributors.txt
data/tree/documents/2010s/2014/fay2014creating/fay2014creating.bib
data/tree/documents/2010s/2014/fay2014creating/fay2014creating.csv

Add fay2014creating from hanachronism	Hannah Little	Sat Mar 31 2018 12:06:10 GMT+0200 (CEST)

Add fay2014creating

---

data/tree/documents/1990s/1996/Isbell_Young_1996/Isbell_Young_1996.bib
data/tree/documents/1990s/1996/Isbell_Young_1996/Isbell_Young_1996.csv
data/tree/documents/1990s/1996/Isbell_Young_1996/contributors.txt

Add Isbell_Young_1996 from seannyD	Sean Roberts	Tue Apr 03 2018 10:01:53 GMT+0100 (BST)	EDIT

Add Isbell_Young_1996

---

data/tree/documents/2010s/2016/hamilton2016diachronic/contributors.txt
data/tree/documents/2010s/2016/hamilton2016diachronic/hamilton2016diachronic.bib
data/tree/documents/2010s/2016/hamilton2016diachronic/hamilton2016diachronic.csv

Add hamilton2016diachronic from AleksandrsBerdicevskis	AleksandrsBerdicevskis	Wed Apr 04 2018 20:52:06 GMT+0200 (W. Europe Daylight Time)

Add hamilton2016diachronic

---

data/tree/documents/2010s/2016/hamilton2016diachronic/contributors.txt
data/tree/documents/2010s/2016/hamilton2016diachronic/hamilton2016diachronic.bib
data/tree/documents/2010s/2016/hamilton2016diachronic/hamilton2016diachronic.csv

Edit hamilton2016diachronic from AleksandrsBerdicevskis	AleksandrsBerdicevskis	Thu Apr 05 2018 16:51:43 GMT+0200 (W. Europe Daylight Time)	EDIT

Edit hamilton2016diachronic

---

data/tree/documents/2010s/2015/futrell2015quantifying/contributors.txt
data/tree/documents/2010s/2015/futrell2015quantifying/futrell2015quantifying.bib
data/tree/documents/2010s/2015/futrell2015quantifying/futrell2015quantifying.csv

Add futrell2015quantifying from AleksandrsBerdicevskis	AleksandrsBerdicevskis	Fri Apr 06 2018 15:05:38 GMT+0200 (W. Europe Daylight Time)

Add futrell2015quantifying

---

data/tree/documents/2010s/2017/simonenko2017taraldsen/contributors.txt
data/tree/documents/2010s/2017/simonenko2017taraldsen/simonenko2017taraldsen.bib
data/tree/documents/2010s/2017/simonenko2017taraldsen/simonenko2017taraldsen.csv

Add simonenko2017taraldsen from AleksandrsBerdicevskis	AleksandrsBerdicevskis	Fri Apr 06 2018 15:30:59 GMT+0200 (W. Europe Daylight Time)

Add simonenko2017taraldsen

---

data/tree/documents/2010s/2011/wichmann2011phonological/contributors.txt
data/tree/documents/2010s/2011/wichmann2011phonological/wichmann2011phonological.bib
data/tree/documents/2010s/2011/wichmann2011phonological/wichmann2011phonological.csv

Add wichmann2011phonological from j-winters	j-winters	Sat Apr 21 2018 12:41:08 GMT+0200 (W. Europe Summer Time)

Add wichmann2011phonological

---

data/tree/documents/1980s/1982/Whiting1982/Whiting1982.csv

You'll need to check I got the specifications right. This paper found that:
1. "Winter temperature of 10C has acted as a barrier to migration"
- which I've operationalised as a n-m relationship of 10c making a barrier.
2. "The homogeneity of the winter temperature variation within the scale we have
adopted suggests that winter temperature may have an important limiting effect
on migration in all climates"
- which I've operationalised as climate: temperature having a negative effect on migration.

Update Causal links in Whiting et al 1982

---

data/tree/documents/2010s/2015/tamariz2015culture/contributors.txt
data/tree/documents/2010s/2015/tamariz2015culture/tamariz2015culture.bib
data/tree/documents/2010s/2015/tamariz2015culture/tamariz2015culture.csv

Add tamariz2015culture from mtamariz	Monica Tamariz	Sun Apr 22 2018 20:24:38 GMT+0100 (BST)

Add tamariz2015culture

---

data/tree/documents/2010s/2015/kirby2015compression/contributors.txt
data/tree/documents/2010s/2015/kirby2015compression/kirby2015compression.bib
data/tree/documents/2010s/2015/kirby2015compression/kirby2015compression.csv

Add kirby2015compression from mtamariz	Monica Tamariz	Sun Apr 22 2018 20:37:59 GMT+0100 (BST)

Add kirby2015compression

---

data/tree/documents/2010s/2014/tamariz2014cultural/contributors.txt
data/tree/documents/2010s/2014/tamariz2014cultural/tamariz2014cultural.bib
data/tree/documents/2010s/2014/tamariz2014cultural/tamariz2014cultural.csv

Add tamariz2014cultural from mtamariz	Monica Tamariz	Sun Apr 22 2018 20:55:11 GMT+0100 (BST)

Add tamariz2014cultural

---

data/tree/documents/2000s/2008/tamariz2008exploring/contributors.txt
data/tree/documents/2000s/2008/tamariz2008exploring/tamariz2008exploring.bib
data/tree/documents/2000s/2008/tamariz2008exploring/tamariz2008exploring.csv

Add tamariz2008exploring from mtamariz	Monica Tamariz	Sun Apr 22 2018 21:16:47 GMT+0100 (BST)

Add tamariz2008exploring

---

data/tree/documents/2010s/2010/tamariz2010role/contributors.txt
data/tree/documents/2010s/2010/tamariz2010role/tamariz2010role.bib
data/tree/documents/2010s/2010/tamariz2010role/tamariz2010role.csv

Add tamariz2010role from mtamariz	Monica Tamariz	Sun Apr 22 2018 21:20:37 GMT+0100 (BST)

Add tamariz2010role

---

data/tree/documents/2010s/2014/maitz_2014/contributors.txt
data/tree/documents/2010s/2014/maitz_2014/maitz_2014.bib
data/tree/documents/2010s/2014/maitz_2014/maitz_2014.csv

Edit maitz_2014 from AleksandrsBerdicevskis	Aleksandrs Berdicevskis	Thu Apr 26 2018 16:32:40 GMT+0200 (W. Europe Daylight Time)	EDIT

Edit maitz_2014

---

data/tree/documents/1980s/1985/kalmar1985there/contributors.txt
data/tree/documents/1980s/1985/kalmar1985there/kalmar1985there.bib
data/tree/documents/1980s/1985/kalmar1985there/kalmar1985there.csv

Add kalmar1985there from AleksandrsBerdicevskis	Aleksandrs Berdicevskis	Fri Apr 27 2018 14:00:05 GMT+0200 (W. Europe Daylight Time)

Add kalmar1985there

---

data/tree/documents/2010s/2011/atkinson2011phonemic/atkinson2011phonemic.bib
data/tree/documents/2010s/2011/atkinson2011phonemic/atkinson2011phonemic.csv
data/tree/documents/2010s/2011/atkinson2011phonemic/contributors.txt

Add atkinson2011phonemic from robross45	robross45	Sat Apr 28 2018 17:18:44 GMT-0400 (EDT)

Add atkinson2011phonemic

---

data/tree/documents/2000s/2008/atkinson2008languages/atkinson2008languages.bib
data/tree/documents/2000s/2008/atkinson2008languages/atkinson2008languages.csv
data/tree/documents/2000s/2008/atkinson2008languages/contributors.txt

Add atkinson2008languages from robross45	robross45	Sat Apr 28 2018 17:55:00 GMT-0400 (EDT)

Add atkinson2008languages

---

data/tree/documents/1930s/1935/zipf1935psycho/contributors.txt
data/tree/documents/1930s/1935/zipf1935psycho/zipf1935psycho.bib
data/tree/documents/1930s/1935/zipf1935psycho/zipf1935psycho.csv

Add zipf1935psycho from robross45	robross45	Sat Apr 28 2018 18:18:53 GMT-0400 (EDT)

Add zipf1935psycho

---

data/tree/documents/2010s/2011/piantadosi2011word/contributors.txt
data/tree/documents/2010s/2011/piantadosi2011word/piantadosi2011word.bib
data/tree/documents/2010s/2011/piantadosi2011word/piantadosi2011word.csv

Add piantadosi2011word from robross45	robross45	Sat Apr 28 2018 18:25:30 GMT-0400 (EDT)

Add piantadosi2011word

---

data/tree/documents/2010s/2013/pagel2013ultraconserved/contributors.txt
data/tree/documents/2010s/2013/pagel2013ultraconserved/pagel2013ultraconserved.bib
data/tree/documents/2010s/2013/pagel2013ultraconserved/pagel2013ultraconserved.csv

Add pagel2013ultraconserved from robross45	robross45	Sat Apr 28 2018 21:38:20 GMT-0400 (EDT)

Add pagel2013ultraconserved

---

data/tree/documents/1990s/1992/Dunbar1992/Dunbar1992.bib
data/tree/documents/1990s/1992/Dunbar1992/contributors.txt

Edit Dunbar1992 from seannyD	Sean Roberts	Fri May 25 2018 21:48:06 GMT+0100 (BST)	EDIT

Edit Dunbar1992

---

data/tree/documents/2010s/2012/gong2012studying/contributors.txt
data/tree/documents/2010s/2012/gong2012studying/gong2012studying.bib
data/tree/documents/2010s/2012/gong2012studying/gong2012studying.csv

Add gong2012studying from jsegoviamartin	Jose Segovia Martin	Fri Jun 15 2018 17:16:28 GMT+0100 (GMT Daylight Time)

Add gong2012studying

---

data/tree/documents/2010s/2013/mueller2013general/contributors.txt
data/tree/documents/2010s/2013/mueller2013general/mueller2013general.bib
data/tree/documents/2010s/2013/mueller2013general/mueller2013general.csv

Add mueller2013general from jsegoviamartin	Jose Segovia Martin	Fri Jun 15 2018 22:31:44 GMT+0100 (GMT Daylight Time)

Add mueller2013general

---

data/tree/documents/2010s/2018/baechler2018absolute/baechler2018absolute.bib
data/tree/documents/2010s/2018/baechler2018absolute/baechler2018absolute.csv
data/tree/documents/2010s/2018/baechler2018absolute/contributors.txt

Add baechler2018absolute from sinnemaki	Kaius Sinnemäki	Tue Jun 19 2018 13:26:18 GMT+0300 (Eastern European Summer Time)

Add baechler2018absolute

---

data/tree/documents/2000s/2008/dammel2008complexity/contributors.txt
data/tree/documents/2000s/2008/dammel2008complexity/dammel2008complexity.bib
data/tree/documents/2000s/2008/dammel2008complexity/dammel2008complexity.csv

Add dammel2008complexity from sinnemaki	Kaius Sinnemäki	Tue Jun 19 2018 13:37:43 GMT+0300 (Eastern European Summer Time)

Add dammel2008complexity

---

data/tree/documents/2010s/2016/nichols2016/contributors.txt
data/tree/documents/2010s/2016/nichols2016/nichols2016.bib
data/tree/documents/2010s/2016/nichols2016/nichols2016.csv

Add nichols2016 from sinnemaki	Kaius Sinnemäki	Tue Jun 19 2018 13:50:40 GMT+0300 (Eastern European Summer Time)

Add nichols2016

---

data/tree/documents/2010s/2018/sinnemakidigarbo2018/contributors.txt
data/tree/documents/2010s/2018/sinnemakidigarbo2018/sinnemakidigarbo2018.bib
data/tree/documents/2010s/2018/sinnemakidigarbo2018/sinnemakidigarbo2018.csv

Add sinnemakidigarbo2018 from sinnemaki	Kaius Sinnemäki	Tue Jun 19 2018 14:01:01 GMT+0300 (Eastern European Summer Time)

Add sinnemakidigarbo2018

---

data/tree/documents/2010s/2013/ferdinand2013regularization/contributors.txt
data/tree/documents/2010s/2013/ferdinand2013regularization/ferdinand2013regularization.bib
data/tree/documents/2010s/2013/ferdinand2013regularization/ferdinand2013regularization.csv

Add ferdinand2013regularization from jsegoviamartin	Jose Segovia Martin	Tue Jun 19 2018 18:52:11 GMT+0100 (GMT Daylight Time)

Add ferdinand2013regularization

---

data/tree/documents/2000s/2005/lee2005role/contributors.txt
data/tree/documents/2000s/2005/lee2005role/lee2005role.bib
data/tree/documents/2000s/2005/lee2005role/lee2005role.csv

Add lee2005role from jsegoviamartin	Jose Segovia Martin	Tue Jun 19 2018 21:04:32 GMT+0100 (GMT Daylight Time)

Add lee2005role

---

data/tree/documents/2000s/2008/aronoff2008language/aronoff2008language.bib
data/tree/documents/2000s/2008/aronoff2008language/aronoff2008language.csv
data/tree/documents/2000s/2008/aronoff2008language/contributors.txt

Add aronoff2008language from catherinesheard	Catherine Sheard	Thu Jun 21 2018 18:51:22 GMT+0100 (BST)

Add aronoff2008language

---

data/tree/documents/2010s/2012/baronchelli_biological_2012/baronchelli_biological_2012.bib
data/tree/documents/2010s/2012/baronchelli_biological_2012/baronchelli_biological_2012.csv
data/tree/documents/2010s/2012/baronchelli_biological_2012/contributors.txt

Add baronchelli_biological_2012 from evoling	Michael Dunn	Sat Jun 23 2018 08:52:38 GMT+0200 (CEST)

Add baronchelli_biological_2012

---

data/tree/documents/1990s/1995/Nettle1995/Nettle1995.bib
data/tree/documents/1990s/1995/Nettle1995/Nettle1995.csv
data/tree/documents/1990s/1995/Nettle1995/contributors.txt

Add Nettle1995 from SimonGreenhill	Simon J Greenhill	Mon Jun 25 2018 12:32:37 GMT+0200 (CEST)

Add Nettle1995

---

data/tree/documents/2010s/2018/Greenhill2018/Greenhill2018.bib
data/tree/documents/2010s/2018/Greenhill2018/Greenhill2018.csv
data/tree/documents/2010s/2018/Greenhill2018/contributors.txt

Add Greenhill2018 from SimonGreenhill	Simon J Greenhill	Mon Jun 25 2018 13:27:42 GMT+0200 (CEST)

Add Greenhill2018

---

data/tree/documents/1990s/1999/Nettle1999a/Nettle1999a.bib
data/tree/documents/1990s/1999/Nettle1999a/Nettle1999a.csv
data/tree/documents/1990s/1999/Nettle1999a/contributors.txt

Add Nettle1999a from SimonGreenhill	Simon J Greenhill	Mon Jun 25 2018 13:42:15 GMT+0200 (CEST)

Add Nettle1999a

---

data/tree/documents/2010s/2017/Everett2017/Everett2017.bib
data/tree/documents/2010s/2017/Everett2017/Everett2017.csv
data/tree/documents/2010s/2017/Everett2017/contributors.txt

Add Everett2017 from SimonGreenhill	Simon J Greenhill	Tue Jun 26 2018 18:06:13 GMT+0200 (CEST)

Add Everett2017

---

data/tree/documents/2010s/2015/Everett2015/Everett2015.bib
data/tree/documents/2010s/2015/Everett2015/Everett2015.csv
data/tree/documents/2010s/2015/Everett2015/contributors.txt

Add Everett2015 from SimonGreenhill	Simon J Greenhill	Wed Jun 27 2018 01:22:09 GMT+0200 (CEST)

Add Everett2015

---

data/tree/documents/2000s/2005/lee2005role/contributors.txt
data/tree/documents/2000s/2005/lee2005role/lee2005role.bib
data/tree/documents/2000s/2005/lee2005role/lee2005role.csv

Edit lee2005role from jsegoviamartin	Jose Segovia Martin	Wed Jun 27 2018 15:56:38 GMT+0100 (GMT Daylight Time)	EDIT

Edit lee2005role

---

data/tree/documents/1970s/1970/goody1970cousin/contributors.txt
data/tree/documents/1970s/1970/goody1970cousin/goody1970cousin.bib
data/tree/documents/1970s/1970/goody1970cousin/goody1970cousin.csv

Add goody1970cousin from SamPassmore	SamPassmore	Thu Jun 28 2018 15:20:28 GMT+0100 (BST)

Add goody1970cousin

---

data/tree/documents/2010s/2018/reali2018simpler/contributors.txt
data/tree/documents/2010s/2018/reali2018simpler/reali2018simpler.bib
data/tree/documents/2010s/2018/reali2018simpler/reali2018simpler.csv

Add reali2018simpler from Etcolquhoun	Etcolquhoun	Fri Jul 13 2018 12:42:08 GMT+0100 (British Summer Time)

Add reali2018simpler

---

data/tree/documents/2010s/2010/kline2010population/contributors.txt
data/tree/documents/2010s/2010/kline2010population/kline2010population.bib
data/tree/documents/2010s/2010/kline2010population/kline2010population.csv

Add kline2010population from jsegoviamartin	Jose Segovia Martin	Mon Jul 16 2018 13:23:46 GMT+0100 (GMT Daylight Time)

Add kline2010population

---

data/tree/documents/2010s/2018/derex2018divide/contributors.txt
data/tree/documents/2010s/2018/derex2018divide/derex2018divide.bib
data/tree/documents/2010s/2018/derex2018divide/derex2018divide.csv

Add derex2018divide from jsegoviamartin	Jose Segovia Martin	Mon Jul 16 2018 13:35:20 GMT+0100 (GMT Daylight Time)

Add derex2018divide

---

data/tree/documents/2010s/2014/GavinStepp2014/GavinStepp2014.bib
data/tree/documents/2010s/2014/GavinStepp2014/GavinStepp2014.csv
data/tree/documents/2010s/2014/GavinStepp2014/contributors.txt

Add GavinStepp2014 from SimonGreenhill	Simon J Greenhill	Thu Aug 09 2018 12:57:23 GMT+0200 (CEST)

Add GavinStepp2014

---

data/tree/documents/2010s/2013/stanford_pan_2013/contributors.txt
data/tree/documents/2010s/2013/stanford_pan_2013/stanford_pan_2013.bib
data/tree/documents/2010s/2013/stanford_pan_2013/stanford_pan_2013.csv

Add stanford_pan_2013 from HedvigS	Hedvig Skirgård	Thu Aug 16 2018 13:18:03 GMT+0200 (Central European Summer Time)

Add stanford_pan_2013

---

data/tree/documents/2010s/2018/jakiela_ozier_2018/contributors.txt
data/tree/documents/2010s/2018/jakiela_ozier_2018/jakiela_ozier_2018.bib
data/tree/documents/2010s/2018/jakiela_ozier_2018/jakiela_ozier_2018.csv

Add jakiela_ozier_2018 from HedvigS	Hedvig Skirgård	Thu Aug 16 2018 20:38:18 GMT+0200 (Central European Summer Time)

Add jakiela_ozier_2018

---

data/tree/documents/2010s/2012/gorenflo2012co/contributors.txt
data/tree/documents/2010s/2012/gorenflo2012co/gorenflo2012co.bib
data/tree/documents/2010s/2012/gorenflo2012co/gorenflo2012co.csv

Add gorenflo2012co from lindellb	lindellb	Wed Aug 22 2018 14:42:07 GMT+1000 (AEST)

Add gorenflo2012co

---

data/tree/documents/2010s/2010/colonna2010long/colonna2010long.bib
data/tree/documents/2010s/2010/colonna2010long/colonna2010long.csv
data/tree/documents/2010s/2010/colonna2010long/contributors.txt

Add colonna2010long from lindellb	lindellb	Wed Aug 22 2018 21:20:56 GMT+1000 (AEST)

Add colonna2010long

---

data/tree/documents/2010s/2018/derungs2018environmental/contributors.txt
data/tree/documents/2010s/2018/derungs2018environmental/derungs2018environmental.bib
data/tree/documents/2010s/2018/derungs2018environmental/derungs2018environmental.csv

Add derungs2018environmental from lindellb	lindellb	Tue Aug 28 2018 14:11:21 GMT+1000 (AEST)

Add derungs2018environmental

---

data/tree/documents/2010s/2013/meguerditchian2013origins/contributors.txt
data/tree/documents/2010s/2013/meguerditchian2013origins/meguerditchian2013origins.bib
data/tree/documents/2010s/2013/meguerditchian2013origins/meguerditchian2013origins.csv

Add meguerditchian2013origins from lindellb	lindellb	Wed Aug 29 2018 12:59:11 GMT+1000 (AEST)

Add meguerditchian2013origins

---

data/tree/documents/2010s/2017/palmer2017does/contributors.txt
data/tree/documents/2010s/2017/palmer2017does/palmer2017does.bib
data/tree/documents/2010s/2017/palmer2017does/palmer2017does.csv

Add palmer2017does from Jonas-N	Jonas Nölle	Tue Sep 11 2018 14:00:47 GMT+0200 (W. Europe Daylight Time)

Add palmer2017does

---

data/tree/documents/2010s/2015/palmer2015topography/contributors.txt
data/tree/documents/2010s/2015/palmer2015topography/palmer2015topography.bib
data/tree/documents/2010s/2015/palmer2015topography/palmer2015topography.csv

Add palmer2015topography from Jonas-N	Jonas Nölle	Tue Sep 11 2018 14:17:08 GMT+0200 (W. Europe Daylight Time)

Add palmer2015topography

---

data/tree/documents/2010s/2017/Blasi_Moran_SLE_2017/Blasi_Moran_SLE_2017.csv
data/tree/documents/2010s/2017/Blasi_Moran_SLE_2017/contributors.txt

Edit Blasi_Moran_SLE_2017 from antonkillin	Anton Killin	Fri Sep 14 2018 23:23:22 GMT+0930 (Australian Central Standard Time)	EDIT

Edit Blasi_Moran_SLE_2017

---

data/tree/documents/2000s/2009/reali2009evolution/contributors.txt
data/tree/documents/2000s/2009/reali2009evolution/reali2009evolution.bib
data/tree/documents/2000s/2009/reali2009evolution/reali2009evolution.csv

Add reali2009evolution from jsegoviamartin	Jose Segovia Martin	Sat Sep 22 2018 11:15:39 GMT+0100 (GMT Daylight Time)

Add reali2009evolution

---

data/tree/documents/2010s/2017/creanza2017greater/contributors.txt
data/tree/documents/2010s/2017/creanza2017greater/creanza2017greater.bib
data/tree/documents/2010s/2017/creanza2017greater/creanza2017greater.csv

Add creanza2017greater from jsegoviamartin	Jose Segovia Martin	Sun Sep 23 2018 14:28:02 GMT+0100 (GMT Daylight Time)

Add creanza2017greater

---

data/tree/documents/2010s/2018/zuidema2018evolution/contributors.txt
data/tree/documents/2010s/2018/zuidema2018evolution/zuidema2018evolution.bib
data/tree/documents/2010s/2018/zuidema2018evolution/zuidema2018evolution.csv

Add zuidema2018evolution from antonkillin	Anton Killin	Fri Sep 28 2018 12:55:33 GMT+1000 (Australian Eastern Standard Time)

Add zuidema2018evolution

---

data/tree/documents/1990s/1998/pederson1998semantic/contributors.txt
data/tree/documents/1990s/1998/pederson1998semantic/pederson1998semantic.bib
data/tree/documents/1990s/1998/pederson1998semantic/pederson1998semantic.csv

Add pederson1998semantic from Jonas-N	Jonas Nölle	Fri Sep 28 2018 16:07:14 GMT+0100 (GMT Daylight Time)

Add pederson1998semantic

---

data/tree/documents/1990s/1993/haviland1993anchoring/contributors.txt
data/tree/documents/1990s/1993/haviland1993anchoring/haviland1993anchoring.bib
data/tree/documents/1990s/1993/haviland1993anchoring/haviland1993anchoring.csv

Add haviland1993anchoring from Jonas-N	Jonas Nölle	Fri Sep 28 2018 16:07:38 GMT+0100 (GMT Daylight Time)

Add haviland1993anchoring

---

data/tree/documents/1990s/1993/brown1993uphill/brown1993uphill.bib
data/tree/documents/1990s/1993/brown1993uphill/brown1993uphill.csv
data/tree/documents/1990s/1993/brown1993uphill/contributors.txt

Add brown1993uphill from Jonas-N	Jonas Nölle	Fri Sep 28 2018 16:25:26 GMT+0100 (GMT Daylight Time)

Add brown1993uphill

---

data/tree/documents/2000s/2002/li2002turning/contributors.txt
data/tree/documents/2000s/2002/li2002turning/li2002turning.bib
data/tree/documents/2000s/2002/li2002turning/li2002turning.csv

Add li2002turning from Jonas-N	Jonas Nölle	Fri Sep 28 2018 16:36:28 GMT+0100 (GMT Daylight Time)

Add li2002turning

---

data/tree/documents/2010s/2018/li2018competing/contributors.txt
data/tree/documents/2010s/2018/li2018competing/li2018competing.bib
data/tree/documents/2010s/2018/li2018competing/li2018competing.csv

Add li2018competing from Jonas-N	Jonas Nölle	Fri Sep 28 2018 17:41:43 GMT+0100 (GMT Daylight Time)

Add li2018competing

---

data/tree/documents/2000s/2009/bjork2009good/bjork2009good.bib
data/tree/documents/2000s/2009/bjork2009good/bjork2009good.csv
data/tree/documents/2000s/2009/bjork2009good/contributors.txt

Add bjork2009good from jsegoviamartin	Jose Segovia Martin	Wed Oct 24 2018 11:57:40 GMT+0100 (Western European Summer Time)

Add bjork2009good

---

data/tree/documents/2000s/2009/goldwater2009bayesian/contributors.txt
data/tree/documents/2000s/2009/goldwater2009bayesian/goldwater2009bayesian.bib
data/tree/documents/2000s/2009/goldwater2009bayesian/goldwater2009bayesian.csv

Add goldwater2009bayesian from jsegoviamartin	Jose Segovia Martin	Wed Oct 24 2018 13:12:51 GMT+0100 (Western European Summer Time)

Add goldwater2009bayesian

---

data/tree/documents/2000s/2004/henrich2004demography/contributors.txt
data/tree/documents/2000s/2004/henrich2004demography/henrich2004demography.bib
data/tree/documents/2000s/2004/henrich2004demography/henrich2004demography.csv

Add henrich2004demography from jsegoviamartin	Jose Segovia Martin	Sun Dec 09 2018 16:04:51 GMT+0000 (GMT)

Add henrich2004demography

---

data/tree/documents/2010s/2012/levi2012tristes/contributors.txt
data/tree/documents/2010s/2012/levi2012tristes/levi2012tristes.bib
data/tree/documents/2010s/2012/levi2012tristes/levi2012tristes.csv

Add levi2012tristes from KitOpie	KitOpie	Wed Dec 12 2018 15:00:11 GMT+0000 (GMT)

Add levi2012tristes

---

data/tree/documents/1990s/1997/smith1997major/contributors.txt
data/tree/documents/1990s/1997/smith1997major/smith1997major.bib
data/tree/documents/1990s/1997/smith1997major/smith1997major.csv

Add smith1997major from KitOpie	KitOpie	Wed Dec 12 2018 15:16:35 GMT+0000 (GMT)

Add smith1997major

---

data/tree/documents/1990s/1997/smith1997major/contributors.txt
data/tree/documents/1990s/1997/smith1997major/smith1997major.bib
data/tree/documents/1990s/1997/smith1997major/smith1997major.csv

Edit smith1997major from KitOpie	KitOpie	Thu Dec 13 2018 15:15:20 GMT+0000 (GMT)	EDIT

Edit smith1997major

---

data/tree/documents/2010s/2017/li2017does/contributors.txt
data/tree/documents/2010s/2017/li2017does/li2017does.bib
data/tree/documents/2010s/2017/li2017does/li2017does.csv

Add li2017does from angarikadeb	angarikadeb	Fri Dec 14 2018 17:37:10 GMT+0530 (India Standard Time)

Add li2017does

---

data/tree/documents/2010s/2017/simonenko2017taraldsen/contributors.txt
data/tree/documents/2010s/2017/simonenko2017taraldsen/simonenko2017taraldsen.bib
data/tree/documents/2010s/2017/simonenko2017taraldsen/simonenko2017taraldsen.csv

Edit simonenko2017taraldsen from angarikadeb	angarikadeb	Fri Dec 14 2018 20:40:25 GMT+0530 (India Standard Time)	EDIT

Edit simonenko2017taraldsen

---

data/tree/documents/2010s/2017/perez2017language/contributors.txt
data/tree/documents/2010s/2017/perez2017language/perez2017language.bib
data/tree/documents/2010s/2017/perez2017language/perez2017language.csv

Add perez2017language from angarikadeb	angarikadeb	Sat Dec 15 2018 01:07:20 GMT+0530 (India Standard Time)

Add perez2017language

---

data/tree/documents/2010s/2015/bowern2015linguistics/bowern2015linguistics.bib
data/tree/documents/2010s/2015/bowern2015linguistics/bowern2015linguistics.csv
data/tree/documents/2010s/2015/bowern2015linguistics/contributors.txt

Add bowern2015linguistics from catherinesheard	Catherine Sheard	Fri Jan 04 2019 18:55:35 GMT+0000 (Greenwich Mean Time)

Add bowern2015linguistics

---

data/tree/documents/2000s/2006/arnold2006language/arnold2006language.bib
data/tree/documents/2000s/2006/arnold2006language/arnold2006language.csv
data/tree/documents/2000s/2006/arnold2006language/contributors.txt

Add arnold2006language from catherinesheard	Catherine Sheard	Thu Jan 10 2019 17:48:16 GMT+0000 (Greenwich Mean Time)

Add arnold2006language

---

data/tree/documents/2010s/2015/majid2015semantic/contributors.txt
data/tree/documents/2010s/2015/majid2015semantic/majid2015semantic.bib
data/tree/documents/2010s/2015/majid2015semantic/majid2015semantic.csv

Add majid2015semantic from catherinesheard	Catherine Sheard	Thu Jan 10 2019 18:08:42 GMT+0000 (Greenwich Mean Time)

Add majid2015semantic

---

data/tree/documents/2000s/2009/basu2009memory/basu2009memory.bib
data/tree/documents/2000s/2009/basu2009memory/basu2009memory.csv
data/tree/documents/2000s/2009/basu2009memory/contributors.txt

Add basu2009memory from KitOpie	KitOpie	Fri Feb 15 2019 14:15:48 GMT+0000 (GMT)

Add basu2009memory

---

data/tree/documents/2000s/2000/smith2000origins/contributors.txt
data/tree/documents/2000s/2000/smith2000origins/smith2000origins.bib
data/tree/documents/2000s/2000/smith2000origins/smith2000origins.csv

Add smith2000origins from KitOpie	KitOpie	Fri Feb 15 2019 15:35:15 GMT+0000 (GMT)

Add smith2000origins

---

data/tree/documents/2000s/2005/van2005language/contributors.txt
data/tree/documents/2000s/2005/van2005language/van2005language.bib
data/tree/documents/2000s/2005/van2005language/van2005language.csv

Add van2005language from ArchieH-B	ArchieH-B	Wed Feb 20 2019 14:01:07 GMT+0000 (Greenwich Mean Time)

Add van2005language

---

data/tree/documents/1980s/1986/kroll1986lexical/contributors.txt
data/tree/documents/1980s/1986/kroll1986lexical/kroll1986lexical.bib
data/tree/documents/1980s/1986/kroll1986lexical/kroll1986lexical.csv

Add kroll1986lexical from seannyD	Sean Roberts	Mon Feb 25 2019 14:45:31 GMT+0000 (Greenwich Mean Time)

Add kroll1986lexical

---

data/tree/documents/1990s/1999/walker1999concrete/contributors.txt
data/tree/documents/1990s/1999/walker1999concrete/walker1999concrete.bib
data/tree/documents/1990s/1999/walker1999concrete/walker1999concrete.csv

Add walker1999concrete from seannyD	Sean Roberts	Mon Feb 25 2019 14:17:27 GMT+0000 (Greenwich Mean Time)

Add walker1999concrete

---

data/tree/documents/2010s/2018/onnis2018language/contributors.txt
data/tree/documents/2010s/2018/onnis2018language/onnis2018language.bib
data/tree/documents/2010s/2018/onnis2018language/onnis2018language.csv

Add onnis2018language from ArchieH-B	ArchieH-B	Wed Feb 27 2019 11:16:40 GMT+0000 (Greenwich Mean Time)

Add onnis2018language

---

data/tree/documents/2010s/2017/crespi2017segregating/contributors.txt
data/tree/documents/2010s/2017/crespi2017segregating/crespi2017segregating.bib
data/tree/documents/2010s/2017/crespi2017segregating/crespi2017segregating.csv

Add crespi2017segregating from ArchieH-B	ArchieH-B	Wed Feb 27 2019 11:35:39 GMT+0000 (Greenwich Mean Time)

Add crespi2017segregating

---

data/tree/documents/2010s/2018/mcnamara2018dopamine/contributors.txt
data/tree/documents/2010s/2018/mcnamara2018dopamine/mcnamara2018dopamine.bib
data/tree/documents/2010s/2018/mcnamara2018dopamine/mcnamara2018dopamine.csv

Add mcnamara2018dopamine from antonkillin	Anton Killin	Fri Mar 01 2019 16:58:53 GMT+1100 (Australian Eastern Daylight Time)

Add mcnamara2018dopamine

---

data/tree/documents/2000s/2008/crawford08/contributors.txt
data/tree/documents/2000s/2008/crawford08/crawford08.bib
data/tree/documents/2000s/2008/crawford08/crawford08.csv

Add crawford08 from EAGasser	Emily Gasser	Sat Mar 16 2019 21:22:18 GMT-0400 (Eastern Daylight Time)

Add crawford08

---

data/tree/documents/2010s/2011/little2011role/contributors.txt
data/tree/documents/2010s/2011/little2011role/little2011role.bib
data/tree/documents/2010s/2011/little2011role/little2011role.csv

Edit little2011role from seannyD	Sean Roberts	Tue Mar 26 2019 14:23:09 GMT+0000 (Greenwich Mean Time)	EDIT

Edit little2011role

---

data/tree/documents/2000s/2005/ameel2005bilinguals/ameel2005bilinguals.bib
data/tree/documents/2000s/2005/ameel2005bilinguals/ameel2005bilinguals.csv
data/tree/documents/2000s/2005/ameel2005bilinguals/contributors.txt

Add ameel2005bilinguals from angarikadeb	angarikadeb	Thu Mar 28 2019 18:28:08 GMT+0000 (Greenwich Mean Time)

Add ameel2005bilinguals

---

data/tree/documents/2000s/2004/kemmelmeier2004language/contributors.txt
data/tree/documents/2000s/2004/kemmelmeier2004language/kemmelmeier2004language.bib
data/tree/documents/2000s/2004/kemmelmeier2004language/kemmelmeier2004language.csv

Add kemmelmeier2004language from angarikadeb	angarikadeb	Fri Mar 29 2019 08:32:31 GMT+0000 (Greenwich Mean Time)

Add kemmelmeier2004language

---

data/tree/documents/2000s/2009/perez2009lost/contributors.txt
data/tree/documents/2000s/2009/perez2009lost/perez2009lost.bib
data/tree/documents/2000s/2009/perez2009lost/perez2009lost.csv

Add perez2009lost from angarikadeb	angarikadeb	Fri Mar 29 2019 11:39:33 GMT+0000 (Greenwich Mean Time)

Add perez2009lost

---

data/tree/documents/2000s/2009/kandler2009investigation/contributors.txt
data/tree/documents/2000s/2009/kandler2009investigation/kandler2009investigation.bib
data/tree/documents/2000s/2009/kandler2009investigation/kandler2009investigation.csv

Add kandler2009investigation from jsegoviamartin	Segovia Martin, Jose	Wed Jun 19 2019 13:40:33 GMT+0100 (Western European Summer Time)

Add kandler2009investigation

---

data/tree/documents/2010s/2010/skyrms2010signals/contributors.txt
data/tree/documents/2010s/2010/skyrms2010signals/skyrms2010signals.bib
data/tree/documents/2010s/2010/skyrms2010signals/skyrms2010signals.csv

Add skyrms2010signals from matspike	matspike	Thu Jul 04 2019 16:12:27 GMT+0100 (British Summer Time)

Add skyrms2010signals

---

data/tree/documents/2010s/2018/singer2018small/contributors.txt
data/tree/documents/2010s/2018/singer2018small/singer2018small.bib
data/tree/documents/2010s/2018/singer2018small/singer2018small.csv

Add singer2018small from ruthsinger	ruthsinger	Thu Jul 25 2019 17:05:08 GMT+1000 (Australian Eastern Standard Time)

Add singer2018small

---

data/tree/documents/1980s/1986/goody1986logic/contributors.txt
data/tree/documents/1980s/1986/goody1986logic/goody1986logic.bib
data/tree/documents/1980s/1986/goody1986logic/goody1986logic.csv

Add goody1986logic from KitOpie	KitOpie	Mon Jul 29 2019 14:57:04 GMT+0100 (BST)

Add goody1986logic

---

data/tree/documents/1980s/1981/green1981construction/contributors.txt
data/tree/documents/1980s/1981/green1981construction/green1981construction.bib
data/tree/documents/1980s/1981/green1981construction/green1981construction.csv

Add green1981construction from KitOpie	KitOpie	Mon Jul 29 2019 15:10:42 GMT+0100 (BST)

Add green1981construction

---

data/tree/documents/2010s/2019/Dediu2019Aug/Dediu2019Aug.bib
data/tree/documents/2010s/2019/Dediu2019Aug/Dediu2019Aug.csv
data/tree/documents/2010s/2019/Dediu2019Aug/contributors.txt

Add Dediu2019Aug from tpellard	Thomas Pellard	Wed Aug 28 2019 11:51:27 GMT+0000 (Temps universel coordonné)

Add Dediu2019Aug

---

data/tree/documents/2010s/2018/Bentz2018/Bentz2018.bib
data/tree/documents/2010s/2018/Bentz2018/Bentz2018.csv
data/tree/documents/2010s/2018/Bentz2018/contributors.txt

Add Bentz2018 from tpellard	Thomas Pellard	Wed Aug 28 2019 12:10:41 GMT+0000 (Temps universel coordonné)

Add Bentz2018

---

data/tree/documents/2010s/2019/Nikolaev2019/Nikolaev2019.bib
data/tree/documents/2010s/2019/Nikolaev2019/Nikolaev2019.csv
data/tree/documents/2010s/2019/Nikolaev2019/contributors.txt

Add Nikolaev2019 from tpellard	Thomas Pellard	Wed Aug 28 2019 12:18:03 GMT+0000 (Temps universel coordonné)

Add Nikolaev2019

---

data/tree/documents/2010s/2015/Good2015/Good2015.bib
data/tree/documents/2010s/2015/Good2015/Good2015.csv
data/tree/documents/2010s/2015/Good2015/contributors.txt

Add Good2015 from tpellard	Thomas Pellard	Wed Aug 28 2019 12:30:19 GMT+0000 (Temps universel coordonné)

Add Good2015

---

data/tree/documents/2000s/2008/dixon08comparative/contributors.txt
data/tree/documents/2000s/2008/dixon08comparative/dixon08comparative.bib
data/tree/documents/2000s/2008/dixon08comparative/dixon08comparative.csv

Add dixon08comparative from rgyalrong	Guillaume Jacques	Thu Aug 29 2019 09:39:55 GMT+0000 (Temps universel coordonné)

Add dixon08comparative

---

data/tree/documents/2010s/2015/delancey15complexity/contributors.txt
data/tree/documents/2010s/2015/delancey15complexity/delancey15complexity.bib
data/tree/documents/2010s/2015/delancey15complexity/delancey15complexity.csv

Add delancey15complexity from rgyalrong	Guillaume Jacques	Thu Aug 29 2019 14:03:12 GMT+0200 (heure d’été d’Europe centrale)

Add delancey15complexity

---

data/tree/documents/2000s/2003/Diamond597/Diamond597.bib
data/tree/documents/2000s/2003/Diamond597/Diamond597.csv
data/tree/documents/2000s/2003/Diamond597/contributors.txt

Add Diamond597 from rgyalrong	Guillaume Jacques	Thu Aug 29 2019 18:38:55 GMT+0200 (heure d’été d’Europe centrale)

Add Diamond597

---

data/tree/documents/2010s/2019/fergus19otitis/contributors.txt
data/tree/documents/2010s/2019/fergus19otitis/fergus19otitis.bib
data/tree/documents/2010s/2019/fergus19otitis/fergus19otitis.csv

Add fergus19otitis from rgyalrong	Guillaume Jacques	Fri Aug 30 2019 11:24:29 GMT+0200 (heure d’été d’Europe centrale)

Add fergus19otitis

---

data/tree/documents/2010s/2017/garnier17milk/contributors.txt
data/tree/documents/2010s/2017/garnier17milk/garnier17milk.bib
data/tree/documents/2010s/2017/garnier17milk/garnier17milk.csv

Add garnier17milk from rgyalrong	Guillaume Jacques	Fri Aug 30 2019 13:24:36 GMT+0200 (heure d’été d’Europe centrale)

Add garnier17milk

---

data/tree/documents/2010s/2017/Mulleretal2017/Mulleretal2017.bib
data/tree/documents/2010s/2017/Mulleretal2017/Mulleretal2017.csv
data/tree/documents/2010s/2017/Mulleretal2017/contributors.txt

Add Mulleretal2017 from Chouilla	Chouilla	Tue Sep 03 2019 15:04:46 GMT+0200 (heure d’été d’Europe centrale)

Add Mulleretal2017

---

data/tree/documents/2000s/2009/Munroeetal2009/Munroeetal2009.bib
data/tree/documents/2000s/2009/Munroeetal2009/Munroeetal2009.csv
data/tree/documents/2000s/2009/Munroeetal2009/contributors.txt

Add Munroeetal2009 from Chouilla	Chouilla	Wed Sep 04 2019 10:39:30 GMT+0200 (heure d’été d’Europe centrale)

Add Munroeetal2009

---

data/tree/documents/2000s/2007/centola2007homophily/centola2007homophily.bib
data/tree/documents/2000s/2007/centola2007homophily/centola2007homophily.csv
data/tree/documents/2000s/2007/centola2007homophily/contributors.txt

Add centola2007homophily from jsegoviamartin	Segovia Martin, Jose	Thu Sep 05 2019 12:10:01 GMT+0100 (Western European Summer Time)

Add centola2007homophily

---

data/tree/documents/2000s/2007/centola2007complex/centola2007complex.bib
data/tree/documents/2000s/2007/centola2007complex/centola2007complex.csv
data/tree/documents/2000s/2007/centola2007complex/contributors.txt

Add centola2007complex from jsegoviamartin	Segovia Martin, Jose	Thu Sep 05 2019 12:41:48 GMT+0100 (Western European Summer Time)

Add centola2007complex

---

data/tree/documents/2010s/2010/csibra2010recognizing/contributors.txt
data/tree/documents/2010s/2010/csibra2010recognizing/csibra2010recognizing.bib
data/tree/documents/2010s/2010/csibra2010recognizing/csibra2010recognizing.csv

Add csibra2010recognizing from christiankliesch	christiankliesch	Thu Sep 19 2019 23:15:00 GMT+0200 (CEST)

Add csibra2010recognizing

---

data/tree/documents/2000s/2008/SenjuCsibra2008/SenjuCsibra2008.bib
data/tree/documents/2000s/2008/SenjuCsibra2008/SenjuCsibra2008.csv
data/tree/documents/2000s/2008/SenjuCsibra2008/contributors.txt

Add SenjuCsibra2008 from christiankliesch	Christian Kliesch	Sat Sep 21 2019 05:42:23 GMT+0200 (Central European Summer Time)

Add SenjuCsibra2008

---

data/tree/documents/2010s/2019/ferdinand2019cognitive/contributors.txt
data/tree/documents/2010s/2019/ferdinand2019cognitive/ferdinand2019cognitive.bib
data/tree/documents/2010s/2019/ferdinand2019cognitive/ferdinand2019cognitive.csv

Add ferdinand2019cognitive from matspike	matspike	Thu Sep 26 2019 20:22:04 GMT+0100 (British Summer Time)

Add ferdinand2019cognitive

---

data/tree/documents/2010s/2016/spike2016minimal/contributors.txt
data/tree/documents/2010s/2016/spike2016minimal/spike2016minimal.bib
data/tree/documents/2010s/2016/spike2016minimal/spike2016minimal.csv

Add spike2016minimal from matspike	matspike	Thu Sep 26 2019 20:33:32 GMT+0100 (British Summer Time)

Add spike2016minimal

---

data/tree/documents/2000s/2009/haun2009variation/contributors.txt
data/tree/documents/2000s/2009/haun2009variation/haun2009variation.bib
data/tree/documents/2000s/2009/haun2009variation/haun2009variation.csv

Add haun2009variation from Jonas-N	Jonas Nölle	Sat Feb 01 2020 06:22:24 GMT+0000 (Greenwich Mean Time)

Add haun2009variation

---

data/tree/documents/2010s/2019/franco_concept_2019/contributors.txt
data/tree/documents/2010s/2019/franco_concept_2019/franco_concept_2019.bib
data/tree/documents/2010s/2019/franco_concept_2019/franco_concept_2019.csv

Add franco_concept_2019 from BonnieMcLean	Bonnie McLean	Sat Jul 25 2020 15:48:39 GMT+0200 (Central European Summer Time)

Add franco_concept_2019

---

data/tree/documents/1990s/1994/lennon1994relative/contributors.txt
data/tree/documents/1990s/1994/lennon1994relative/lennon1994relative.bib
data/tree/documents/1990s/1994/lennon1994relative/lennon1994relative.csv

Add lennon1994relative from angarikadeb	angarikadeb	Sat Aug 08 2020 19:47:26 GMT+0530 (IST)

Add lennon1994relative

---

data/tree/documents/2020s/2020/hwang2020paid/contributors.txt
data/tree/documents/2020s/2020/hwang2020paid/hwang2020paid.bib
data/tree/documents/2020s/2020/hwang2020paid/hwang2020paid.csv

Add hwang2020paid from angarikadeb	angarikadeb	Sun Aug 09 2020 12:25:40 GMT+0530 (IST)

Add hwang2020paid

---

data/tree/documents/2010s/2016/carriero2016housework/carriero2016housework.bib
data/tree/documents/2010s/2016/carriero2016housework/carriero2016housework.csv
data/tree/documents/2010s/2016/carriero2016housework/contributors.txt

Add carriero2016housework from angarikadeb	angarikadeb	Sun Aug 09 2020 18:33:37 GMT+0530 (IST)

Add carriero2016housework

---

data/tree/documents/2000s/2002/batalova2002premarital/batalova2002premarital.bib
data/tree/documents/2000s/2002/batalova2002premarital/batalova2002premarital.csv
data/tree/documents/2000s/2002/batalova2002premarital/contributors.txt

Add batalova2002premarital from angarikadeb	angarikadeb	Tue Aug 11 2020 09:12:47 GMT+0530 (IST)

Add batalova2002premarital

---

data/tree/documents/2000s/2002/batalova2002premarital/contributors.txt

Edit batalova2002premarital from angarikadeb	angarikadeb	Wed Aug 12 2020 10:40:46 GMT+0530 (IST)

Edit batalova2002premarital

---

data/tree/documents/2010s/2019/dyble2019engagement/contributors.txt
data/tree/documents/2010s/2019/dyble2019engagement/dyble2019engagement.bib
data/tree/documents/2010s/2019/dyble2019engagement/dyble2019engagement.csv

Add dyble2019engagement from angarikadeb	angarikadeb	Wed Aug 12 2020 11:23:44 GMT+0530 (IST)

Add dyble2019engagement

---

data/tree/documents/2010s/2015/chaudhary2015polygyny/chaudhary2015polygyny.bib
data/tree/documents/2010s/2015/chaudhary2015polygyny/chaudhary2015polygyny.csv
data/tree/documents/2010s/2015/chaudhary2015polygyny/contributors.txt

Add chaudhary2015polygyny from angarikadeb	angarikadeb	Wed Aug 12 2020 11:49:40 GMT+0530 (IST)

Add chaudhary2015polygyny

---

data/tree/documents/2010s/2016/smith2016camp/contributors.txt
data/tree/documents/2010s/2016/smith2016camp/smith2016camp.bib
data/tree/documents/2010s/2016/smith2016camp/smith2016camp.csv

Add smith2016camp from angarikadeb	angarikadeb	Wed Aug 12 2020 13:12:30 GMT+0530 (IST)

Add smith2016camp

---

data/tree/documents/2010s/2016/dyble2016networks/contributors.txt
data/tree/documents/2010s/2016/dyble2016networks/dyble2016networks.bib
data/tree/documents/2010s/2016/dyble2016networks/dyble2016networks.csv

Add dyble2016networks from angarikadeb	angarikadeb	Thu Aug 13 2020 12:11:03 GMT+0530 (IST)

Add dyble2016networks

---

data/tree/documents/2010s/2019/smith2019friend/contributors.txt
data/tree/documents/2010s/2019/smith2019friend/smith2019friend.bib
data/tree/documents/2010s/2019/smith2019friend/smith2019friend.csv

Add smith2019friend from angarikadeb	angarikadeb	Thu Aug 13 2020 18:49:23 GMT+0530 (IST)

Add smith2019friend

---

data/tree/documents/2020s/2020/carriero2020role/carriero2020role.bib
data/tree/documents/2020s/2020/carriero2020role/carriero2020role.csv
data/tree/documents/2020s/2020/carriero2020role/contributors.txt

Add carriero2020role from angarikadeb	angarikadeb	Mon Aug 17 2020 11:21:48 GMT+0530 (IST)

Add carriero2020role

---

data/tree/documents/2010s/2011/andre2011evolution/andre2011evolution.bib
data/tree/documents/2010s/2011/andre2011evolution/andre2011evolution.csv
data/tree/documents/2010s/2011/andre2011evolution/contributors.txt

Add andre2011evolution from angarikadeb	angarikadeb	Wed Aug 19 2020 11:27:28 GMT+0530 (IST)

Add andre2011evolution

---

data/tree/documents/2010s/2013/baumard2013mutualistic/baumard2013mutualistic.bib
data/tree/documents/2010s/2013/baumard2013mutualistic/baumard2013mutualistic.csv
data/tree/documents/2010s/2013/baumard2013mutualistic/contributors.txt

Add baumard2013mutualistic from angarikadeb	angarikadeb	Thu Aug 20 2020 08:19:58 GMT+0530 (IST)

Add baumard2013mutualistic

---

data/tree/documents/1980s/1988/broman1988household/broman1988household.bib
data/tree/documents/1980s/1988/broman1988household/broman1988household.csv
data/tree/documents/1980s/1988/broman1988household/contributors.txt

Add broman1988household from angarikadeb	angarikadeb	Thu Aug 20 2020 11:09:00 GMT+0530 (IST)

Add broman1988household

---

data/tree/documents/1980s/1986/cutrona1986objective/contributors.txt
data/tree/documents/1980s/1986/cutrona1986objective/cutrona1986objective.bib
data/tree/documents/1980s/1986/cutrona1986objective/cutrona1986objective.csv

Add cutrona1986objective from angarikadeb	angarikadeb	Thu Aug 20 2020 23:29:56 GMT+0530 (IST)

Add cutrona1986objective

---

data/tree/documents/2000s/2000/greenstein2000economic/contributors.txt
data/tree/documents/2000s/2000/greenstein2000economic/greenstein2000economic.bib
data/tree/documents/2000s/2000/greenstein2000economic/greenstein2000economic.csv

Add greenstein2000economic from angarikadeb	angarikadeb	Fri Aug 21 2020 12:03:20 GMT+0530 (IST)

Add greenstein2000economic

---

data/tree/documents/2000s/2008/charness2008s/charness2008s.bib
data/tree/documents/2000s/2008/charness2008s/charness2008s.csv
data/tree/documents/2000s/2008/charness2008s/contributors.txt

Add charness2008s from angarikadeb	angarikadeb	Mon Aug 24 2020 19:09:28 GMT+0530 (IST)

Add charness2008s

---

data/tree/documents/2010s/2011/andersen2011stakes/andersen2011stakes.bib
data/tree/documents/2010s/2011/andersen2011stakes/andersen2011stakes.csv
data/tree/documents/2010s/2011/andersen2011stakes/contributors.txt

Add andersen2011stakes from angarikadeb	angarikadeb	Mon Aug 24 2020 22:11:06 GMT+0530 (IST)

Add andersen2011stakes

---

data/tree/documents/2020s/2020/aina2020frustration/aina2020frustration.bib
data/tree/documents/2020s/2020/aina2020frustration/aina2020frustration.csv
data/tree/documents/2020s/2020/aina2020frustration/contributors.txt

Add aina2020frustration from angarikadeb	angarikadeb	Tue Aug 25 2020 09:03:14 GMT+0530 (IST)

Add aina2020frustration

---

data/tree/documents/2010s/2019/larney2019stake/contributors.txt
data/tree/documents/2010s/2019/larney2019stake/larney2019stake.bib
data/tree/documents/2010s/2019/larney2019stake/larney2019stake.csv

Add larney2019stake from angarikadeb	angarikadeb	Tue Aug 25 2020 19:52:08 GMT+0530 (IST)

Add larney2019stake

---

data/tree/documents/2010s/2011/engel2011dictator/contributors.txt
data/tree/documents/2010s/2011/engel2011dictator/engel2011dictator.bib
data/tree/documents/2010s/2011/engel2011dictator/engel2011dictator.csv

Add engel2011dictator from angarikadeb	angarikadeb	Tue Aug 25 2020 21:12:33 GMT+0530 (IST)

Add engel2011dictator

---

data/tree/documents/2010s/2015/debove2015partner/contributors.txt
data/tree/documents/2010s/2015/debove2015partner/debove2015partner.bib
data/tree/documents/2010s/2015/debove2015partner/debove2015partner.csv

Add debove2015partner from angarikadeb	angarikadeb	Sat Aug 29 2020 10:52:22 GMT+0530 (IST)

Add debove2015partner

---

data/tree/documents/1990s/1995/knez1995outside/contributors.txt
data/tree/documents/1990s/1995/knez1995outside/knez1995outside.bib
data/tree/documents/1990s/1995/knez1995outside/knez1995outside.csv

Add knez1995outside from angarikadeb	angarikadeb	Sat Aug 29 2020 18:32:04 GMT+0530 (IST)

Add knez1995outside

---

data/tree/documents/2000s/2003/abrams2003modelling/abrams2003modelling.bib
data/tree/documents/2000s/2003/abrams2003modelling/abrams2003modelling.csv
data/tree/documents/2000s/2003/abrams2003modelling/contributors.txt

Add abrams2003modelling from jsegoviamartin	Segovia Martin, Jose	Sat Jan 09 2021 10:54:07 GMT+0100 (Central European Standard Time)

Add abrams2003modelling

---

data/tree/documents/1990s/1992/grace_1992_aberrant/contributors.txt
data/tree/documents/1990s/1992/grace_1992_aberrant/grace_1992_aberrant.bib
data/tree/documents/1990s/1992/grace_1992_aberrant/grace_1992_aberrant.csv

Add grace_1992_aberrant from HedvigS	Hedvig Skirgård	Thu Apr 15 2021 19:09:35 GMT+0200 (CEST)

Add grace_1992_aberrant

---

data/tree/documents/2020s/2022/bromham2022global/bromham2022global.bib
data/tree/documents/2020s/2022/bromham2022global/bromham2022global.csv
data/tree/documents/2020s/2022/bromham2022global/contributors.txt

Add bromham2022global by SamPassmore

Add bromham2022global
